/** Keys present in messages/detailFields — used for safe lookups in generic step bodies. */
export const DETAIL_FIELD_KEYS = new Set([
  "pickupLocation",
  "towingDate",
  "dateTime",
  "reportType",
  "reasonForDamage",
  "reportingParty",
  "contact",
  "expertAssignmentDate",
  "expertInfo",
  "vehicleDuration",
  "vehicleModel",
  "extraDuration",
  "reviewReferralDate",
  "reviewCompletionDate",
  "actionRequired",
  "occupationalDeduction",
  "appreciationDeduction",
  "policyDeductible",
  "nonDamageAmount",
  "paidTo",
  "iban",
  "paymentAmount",
  "note",
  "completionDate",
]);
